# Generated by Django 4.0.4 on 2022-04-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('image_url', models.CharField(max_length=600)),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
